### ISSUE TITLE
Link to the Manhattan data is broken. 

### ISSUE THREAD

**Issue by KL4805** [HKU-Smart-Mobility-Lab/Transportation_Simulator#24]
Hi authors!

It seems that the link https://connecthkuhk-my.sharepoint.com/:f:/g/personal/ctj21_connect_hku_hk/EmQj0_wys2ZCq2MQqNF3BvABr8K8ZQsaK7dsUPw9lCu9EQ?e=HXKx0j is broken. I cannot download from the site. 

Please check, thank you!

**Comment by KL4805** [comment]
In addition, I constantly observe the following error. 
`FileNotFoundError:` [Errno 2] No such file or directory: 'input/graph.graphml'`

Is this caused by the lack of Manhattan data? How to address it?

**Comment by chenhaoling** [comment]
Sorry for the late reply. You can acquire the data and graph.grahml in the following link.
https://connecthkuhk-my.sharepoint.com/:f:/g/personal/ctj21_connect_hku_hk/EuHy9dMKNy1CkZf5K87GMlYBAI54ZPeGzjanbrpBTZO5CQ?e=95BBYF

**Comment by chenhaoling** [comment]
Solved.
