### ISSUE TITLE
Missing file under 'matching' mode

### ISSUE THREAD

**Issue by KL4805** [HKU-Smart-Mobility-Lab/Transportation_Simulator#28]
Hi authors, 

I tried to study matching, and so I set 'rl_mode' to 'matching' in config.py. 

Now, when I start to run `python3 simulator/main.py`, an error popped out

```
Traceback (most recent call last):
  File "simulator/main.py", line 256, in <module>
    pickle.dump(simulator.record,open("output3/order_record-1103.pickle","wb"))
FileNotFoundError: [Errno 2] No such file or directory: 'output3/order_record-1103.pickle'
```

It seems that an important file is missing for running matching. Could you please check?

**Comment by Caffretro** [comment]
It suggests that the directory output3 for file dumping does not exist. You can simply create a directory called output3 or modify any code segments related to file I/O to resolve FileNotFoundErrors.
