### ISSUE TITLE
Would you consider adding more description on the code?

### ISSUE THREAD

**Issue by Fetkou** [HKU-Smart-Mobility-Lab/Transportation_Simulator#35]
Hi, we have a strong interest in your simulation platform, and I have read the paper. I can roughly get the idea of the framework. However, would you consider adding more description on each module function? For example, the description of simulator_env and how it relates to each part. How the RL algorithm is implemented on the simulation part. And there are not too much comments in the code, which makes it a bit hard to read and understand. Would you consider systematically organizing the code and adding more comments? I think this can also help others to access and to enlarge the influence of your platform.

**Comment by chenhaoling** [comment]
Thanks for your interest and suggestions. We have added some comments for nearly every function, however, it seems that it is not enough to help others learn the details of the simulator. We will publish several videos to guide other scholars using the simulator who are interested in this simulator later. Thanks for your suggestions again.

**Comment by Fetkou** [comment]
Thank you for your effort. I understand that if someone wants to use it, they will indeed figure it out anyway, no matter how much time it takes. But if you can make it more accessible, that will be more convenient for us. It will be quite nice if you can make some videos. However, from my own perspective, as a beginner, I would expect to see a whole structure of the code, just like the figure of simulation framework in your paper. To achieve this, I would like to see the input and output of each code file (or module) and how is it organized with others. So that I can know how to call it when I need to test my algorithm, just like APIs. And further, if I would like to modify some mechanism, I know which file I should reach to. Now that all I know is to run the main.py and it does not run successfully if I didn't refer to other issues. And my next step is to chase every part of it to understand the logic of the code. I haven't investigated the details of the code so far, so I am not sure if the comment and modularization is enough. But anyway, thank you for your effort and time, such a platform is indeed needed for researchers.
